name: tracking
description: tracking mobile app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  injectable: ^2.3.2
  flutter_bloc: ^8.1.4
  json_annotation: ^4.8.1
  auto_route: ^7.8.4
  retrofit: ^4.1.0
  dio: ^5.4.1
  logger: ^2.0.2+1
  easy_localization: ^3.0.5
  get_it: ^7.6.7
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  awesome_dio_interceptor: ^1.1.0
  shared_preferences: ^2.2.2
  form_builder_validators: ^9.1.0
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  pretty_dio_logger: ^1.3.1
  path_provider: ^2.1.2
  lottie: ^2.7.0
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  flutter_polyline_points: ^2.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  fluttertoast: ^8.2.2
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.4.1
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/translations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue/BebasNeue-Regular.ttf
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa/Nexa-Regular.otf
        - asset: assets/fonts/nexa/Nexa-Bold.otf
          weight: 700

